import catalog from "./catalog.json";
import type { Asset, DemoState, Order, Wish } from "./model";
const all = catalog.flatMap((c) =>
  c.members.map((m) => ({ ...m, collection: c.name })),
);
export const findSkin = (english: string) =>
  all.find((s) => s.english === english)!;
function asset(id: string, english: string, rest: Partial<Asset>): Asset {
  const s = findSkin(english);
  return {
    id,
    skinId: s.id,
    name: s.name,
    image: s.image,
    rarity: s.rarity,
    wear: "久经沙场",
    float: "0.21836471557617188",
    template: "387",
    version: "普通",
    platform: "BUFF",
    status: "持有中",
    rental: "未出租",
    tags: ["出租"],
    date: "2026-04-30",
    cost: 120000,
    value: 138000,
    sale: 0,
    note: "用于交互验收的虚构记录",
    collection: s.collection,
    kind: "饰品",
    ...rest,
  };
}
export function createDemo(): DemoState {
  const assets: Asset[] = [
    asset("a1", "AWP | Asiimov", {
      platform: "IGXE",
      cost: 339900,
      value: 365000,
      rental: "出租中",
      date: "2026-04-30",
    }),
    asset("a2", "AK-47 | Redline", {
      cost: 128000,
      value: 142000,
      rental: "归还后冷却",
      date: "2026-05-12",
      tags: ["出租", "个人自用"],
    }),
    asset("a3", "AUG | Chameleon", {
      cost: 8800,
      value: 9600,
      wear: "略有磨损",
      float: "0.09253821563720703",
      tags: ["收藏"],
      date: "2026-05-18",
    }),
    asset("a4", "AUG | Chameleon", {
      cost: 18500,
      value: 20500,
      version: "StatTrak™",
      wear: "崭新出厂",
      float: "0.03112946823239326",
      tags: ["收藏"],
      date: "2026-06-02",
    }),
    asset("a5", "USP-S | Guardian", {
      cost: 9500,
      value: null,
      sale: 11200,
      status: "已售出",
      date: "2026-06-08",
      platform: "Steam",
      tags: ["倒余额"],
    }),
    asset("a6", "MP9 | Wild Lily", {
      cost: null,
      value: 1200000,
      platform: "悠悠有品",
      rental: "状态待核实",
      tags: ["收藏"],
      note: "库存观察到此物品，缺取得记录；成本不能视为零。",
      date: "2026-08-12",
    }),
    asset("a7", "AK-47 | Wild Lotus", {
      cost: 0,
      value: 4800000,
      wear: "战痕累累",
      float: "0.61836471557617188",
      platform: "Steam",
      tags: ["收藏", "个人自用"],
      note: "示例受赠资产：明确成本为零，不是未知成本。",
      date: "2026-07-18",
    }),
    asset("a8", "P90 | Trigon", {
      cost: 50000,
      value: null,
      status: "已赠出",
      date: "2026-05-01",
      tags: ["个人自用"],
      note: "赠出示例：成本保留在累计收支差额，不冲减已实现净收益。",
    }),
    {
      id: "e1",
      skinId: "",
      name: "IGXE 平台支出",
      image: "",
      rarity: "#8290a8",
      wear: "—",
      float: "—",
      template: "—",
      version: "普通",
      platform: "IGXE",
      status: "持有中",
      rental: "未出租",
      tags: [],
      date: "2026-08-28",
      cost: 3600,
      value: null,
      sale: 0,
      note: "示例服务费",
      collection: "—",
      kind: "公共收支",
    },
  ];
  const orders: Order[] = assets
    .filter((a) => a.kind === "饰品" && a.cost !== null && a.cost > 0)
    .map((a, i) => ({
      id: `DEMO-B${i + 1}`,
      assetId: a.id,
      name: a.name,
      platform: a.platform!,
      type: "购买",
      status: "已完成",
      amount: a.cost!,
      date: a.date,
      source: "示例平台记录",
      note: "记账日期依据：成功购买订单下单日期",
    }));
  orders.push(
    ...([
      {
        id: "DEMO-R01",
        assetId: "a1",
        name: assets[0].name,
        platform: "IGXE",
        type: "出租",
        status: "已完成",
        amount: 18600,
        date: "2026-06-15",
        source: "示例平台记录",
        term: "长租",
        note: "基础租金 168 元 + 加成 18 元，整单已结清。",
      },
      {
        id: "DEMO-R02",
        assetId: "a1",
        name: assets[0].name,
        platform: "IGXE",
        type: "出租",
        status: "已完成",
        amount: 22400,
        date: "2026-07-26",
        source: "示例平台记录",
        term: "长租",
        note: "最终结算租金；押金不计收入。",
      },
      {
        id: "DEMO-R03",
        assetId: "a2",
        name: assets[1].name,
        platform: "BUFF",
        type: "出租",
        status: "已完成",
        amount: 4500,
        date: "2026-07-12",
        source: "示例平台记录",
        term: "短租",
        note: "已归还且已结算。",
      },
      {
        id: "DEMO-R04",
        assetId: "a2",
        name: assets[1].name,
        platform: "BUFF",
        type: "出租",
        status: "已完成",
        amount: 6700,
        date: "2026-08-24",
        source: "示例平台记录",
        term: "长租",
        note: "续租包含在同一主订单。",
      },
      {
        id: "DEMO-R05",
        assetId: "a8",
        name: assets[7].name,
        platform: "BUFF",
        type: "出租",
        status: "已完成",
        amount: 6000,
        date: "2026-06-12",
        source: "示例平台记录",
        term: "短租",
        note: "赠出前的已结算租金。",
      },
      {
        id: "DEMO-R06",
        assetId: "a1",
        name: assets[0].name,
        platform: "IGXE",
        type: "出租",
        status: "待结算",
        amount: 9800,
        date: "2026-09-12",
        source: "示例平台记录",
        term: "短租",
        note: "预期租金，尚未结束，不计入已实现收入。",
      },
      {
        id: "DEMO-S01",
        assetId: "a5",
        name: assets[4].name,
        platform: "Steam",
        type: "出售",
        status: "已完成",
        amount: 11200,
        date: "2026-09-03",
        source: "示例平台记录",
        note: "CS2 市场钱包净收入；成功出售按下单日记账。",
      },
      {
        id: "DEMO-X01",
        assetId: null,
        name: assets[1].name,
        platform: "BUFF",
        type: "购买",
        status: "失败",
        amount: 125000,
        date: "2026-05-11",
        source: "示例平台记录",
        note: "已取消，不建立资产，不计成本。",
      },
      {
        id: "DEMO-U01",
        assetId: null,
        name: assets[5].name,
        platform: "悠悠有品",
        type: "出租",
        status: "待核对",
        amount: 3800,
        date: "2026-09-01",
        source: "手工补录",
        term: "未知",
        note: "候选实例不唯一；待人工选择关联，不计汇总。",
      },
    ] as Order[]),
  );
  const wishes: Wish[] = [
    {
      id: "w1",
      skinId: findSkin("AK-47 | Wild Lotus").id,
      name: "AK-47 | 野荷",
      image: findSkin("AK-47 | Wild Lotus").image,
      wear: "崭新出厂",
      version: "普通",
      target: 9000000,
      buff: 9649900,
      youpin: 9640000,
      igxe: null,
      special: "",
      currencyKnown: false,
      updated: "2026-09-18 10:30",
    },
    {
      id: "w2",
      skinId: assets[0].skinId,
      name: assets[0].name,
      image: assets[0].image,
      wear: "久经沙场",
      version: "普通",
      target: 380000,
      buff: 365000,
      youpin: 372000,
      igxe: null,
      special: "",
      currencyKnown: true,
      updated: "2026-09-18 10:30",
    },
    {
      id: "w3",
      skinId: assets[1].skinId,
      name: assets[1].name,
      image: assets[1].image,
      wear: "略有磨损",
      version: "普通",
      target: 160000,
      buff: 142000,
      youpin: 149000,
      igxe: null,
      special: "磨损 0.10 以下，模板 387",
      currencyKnown: true,
      updated: "2026-09-18 10:30",
    },
  ];
  return { assets, orders:orders.map(o=>({...o,settledAt:o.type==='出租'&&o.status==='已完成'?o.date:undefined})), wishes:wishes.map(w=>({...w,currencyKnown:true})) };
}
