import { _electron as electron } from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const catalog=JSON.parse(await readFile('src/shared/catalog-bundled.json','utf8'));
const profile=resolve(`artifacts/iteration-profile-${Date.now()}`);await mkdir(profile,{recursive:true});
const env={...process.env,CS_RENT_TEST_DEMO:'1',CS_RENT_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
const app=await electron.launch({args:['out/main/index.js'],env});const page=await app.firstWindow();page.setDefaultTimeout(15000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const go=name=>page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name,exact:true}).click();
const choose=async(label,value)=>{await page.getByRole('dialog').getByLabel(label,{exact:true}).click();await page.locator('.ant-select-item-option-content:visible').getByText(value,{exact:true}).click();};
const screenshot=name=>page.screenshot({path:resolve(`artifacts/${name}.png`),fullPage:true,animations:'disabled'});
try{
  await page.getByRole('heading',{name:'每一件饰品，都有迹可循。'}).waitFor();
  for(const value of ['7天','15天','1月','3月','6月','1年']){await page.locator('.rental-income-panel').getByText(value,{exact:true}).click();assert.equal(await page.getByTestId('rental-total').isVisible(),true);}
  await page.locator('.rental-income-panel').getByText('自定义',{exact:true}).click();
  await page.getByRole('textbox',{name:'租金开始日期'}).fill('2026-01-01');
  await page.getByRole('textbox',{name:'租金结束日期'}).fill('2026-09-18');
  assert.match(await page.getByTestId('rental-total').innerText(),/582\.00/);
  await screenshot('20-rental-income-light');
  await go('愿望单');assert.equal(await page.getByText('币种待确认',{exact:true}).count(),0);
  assert.match(await page.locator('.wish-card').first().locator('.wish-price').innerText(),/[¥￥]96,400\.00/);
  await app.evaluate(({shell})=>{globalThis.openedLinks=[];shell.openExternal=async url=>{globalThis.openedLinks.push(url);};});
  await page.locator('.wish-card').first().locator('.wish-result button').click();
  await page.waitForFunction(()=>!document.querySelector('.wish-result button:disabled'),null,{timeout:40000});
  const opened=await app.evaluate(()=>globalThis.openedLinks);
  assert.match(opened[0],/^https:\/\/www\.youpin898\.com\/market\/goods-list\?/,'真实 SteamDT 页面解析最低报价平台链接');
  assert.match(opened[0],/templateId=48144/);
  await page.getByRole('button',{name:'编辑AK-47 | 红线',exact:true}).click();
  const dialog=page.getByRole('dialog');
  await dialog.getByLabel('磨损上限',{exact:true}).fill('0.1');
  await dialog.getByLabel('图案模板',{exact:true}).fill('387');
  assert.equal(await dialog.getByLabel('渐变率下限（%）',{exact:true}).count(),0);
  await dialog.getByRole('button',{name:'保存愿望',exact:true}).click();await dialog.waitFor({state:'hidden'});
  assert.match(await page.locator('.wish-card').filter({hasText:'AK-47 | 红线'}).innerText(),/图案模板 387/);
  await screenshot('21-wishlist-light');
  const knife=catalog.groups.find(g=>g.id==='knife-500');const vanilla=knife.members.find(s=>s.wears.includes('不适用'));const fade=knife.members.find(s=>s.english==='★ Bayonet | Fade');
  await page.getByRole('button',{name:'添加愿望',exact:true}).click();
  await dialog.getByLabel('商品',{exact:true}).fill(vanilla.name);await page.locator('.ant-select-item-option-content:visible').getByText(vanilla.name,{exact:true}).click();
  assert.equal(await dialog.getByLabel('图案模板',{exact:true}).count(),0);
  await dialog.getByLabel('商品',{exact:true}).fill(fade.name);await page.locator('.ant-select-item-option-content:visible').getByText(fade.name,{exact:true}).click();
  assert.equal(await dialog.getByLabel('渐变率下限（%）',{exact:true}).isVisible(),true);
  await choose('外观','崭新出厂');await dialog.getByLabel('目标买入价（人民币元）',{exact:true}).fill('8000');
  await dialog.getByRole('button',{name:'保存愿望',exact:true}).click();await dialog.waitFor({state:'hidden'});
  await go('收藏室');
  const dates=await page.locator('.collection-sidebar .collection-nav').evaluateAll(nodes=>nodes.map(n=>n.textContent.match(/发行：(\d{4}-\d{2}-\d{2})/)?.[1]).filter(Boolean));
  assert.deepEqual(dates,[...dates].sort().reverse());
  await page.getByRole('button',{name:'放大选择收藏品',exact:true}).click();
  await dialog.getByRole('textbox',{name:'放大目录搜索'}).fill('画廊');
  await screenshot('22-expanded-catalog');await dialog.locator('.collection-nav').click();
  assert.match(await page.locator('.collection-banner').innerText(),/画廊/);assert.match(await page.locator('.availability-box').innerText(),/2025-10-01/);
  await page.getByText('武库通行证',{exact:true}).first().click();
  assert.equal(await page.locator('.collection-sidebar .collection-nav').count(),9);
  await screenshot('23-armory-light');
  const phase1=knife.members.find(s=>s.phase==='Phase 1');const phase2=knife.members.find(s=>s.phase==='Phase 2'&&s.finishKey===phase1.finishKey);
  const gun=catalog.groups.find(g=>g.id==='collection-set-dust-2');const souvenir=gun.members.find(s=>s.souvenir);
  await page.evaluate(async({phase1,phase2,souvenir})=>{const {data:saved}=await window.desktop.data.get();const base=saved.state.assets[0];saved.state.assets.push(...[phase1,phase2,souvenir].map((s,i)=>({...base,id:'iteration-asset-'+i,skinId:s.id,name:s.name,image:s.image,rarity:s.rarity,version:i===2?'纪念品':i===1?'StatTrak™':'普通',wear:s.wears[0],status:'持有中'})));await window.desktop.data.save(saved.state,saved.space);},{phase1,phase2,souvenir});
  await page.reload();await go('收藏室');await page.getByText('刀具 · 按刀型',{exact:true}).click();
  assert.equal(await page.getByTestId('collection-count').innerText(),'1 / 25');
  assert.equal(await page.locator('.owned-phase').count(),2);assert.equal(await page.locator('.phase:not(.owned-phase)').count()>0,true);
  await page.getByRole('button',{name:'切换深色主题',exact:true}).click();
  const dopplerRow=page.locator('.collection-skin').filter({has:page.locator('.owned-phase')}).first();
  await dopplerRow.scrollIntoViewIfNeeded();await screenshot('24-doppler-dark');
  await dopplerRow.locator('button').first().click();
  await page.waitForFunction(()=>!document.querySelector('.collection-item-link:disabled'));
  assert.match((await app.evaluate(()=>globalThis.openedLinks)).at(-1),/^https:\/\/(www\.)?steamdt.com\/cs2\//);
  await page.getByText('枪械收藏品',{exact:true}).click();await page.getByRole('textbox',{name:'搜索收藏分组'}).fill(gun.name);await page.locator('.collection-nav').filter({has:page.getByText(gun.name,{exact:true})}).click();
  assert.match(await page.getByTestId('collection-any-count').innerText(),/已拥有 1 款/);assert.match(await page.getByTestId('collection-count').innerText(),/^0 \/ /);
  assert.equal(await page.getByText(/拥有纪念品 ·/).count(),1);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1050,760));await screenshot('25-collection-small-dark');
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1480,950));
  await go('总览');await screenshot('26-rental-income-dark');
  assert.deepEqual(errors,[]);
  await writeFile('artifacts/iteration-smoke-result.json',JSON.stringify({passed:true,date:new Date().toISOString(),checks:['全部七档租金跨度','按结算日期的自定义总额','默认人民币','最低价悠悠有品真实详情链接','特殊条件可选与不适用隐藏','放大目录和发行日期排序','武库当前及停投日期','多普勒款式点亮且合计去重','收藏品SteamDT跳转','纪念品计入总数但不进入普通进度','深浅主题和窄窗'],openedLinks:await app.evaluate(()=>globalThis.openedLinks),errors},null,2));
  console.log('PASS: v0.4 interactions and live platform-link resolution.');
}catch(e){await screenshot('iteration-failure');await writeFile('artifacts/iteration-failure.txt',await page.locator('body').innerText());throw e;}finally{await app.close();}
