import {_electron as electron} from 'playwright';
import {mkdir,readFile,writeFile,readdir} from 'node:fs/promises';
import {resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(`artifacts/migration-ui-${Date.now()}`);await mkdir(root,{recursive:true});
const catalog=JSON.parse(await readFile('src/shared/catalog-bundled.json','utf8'));
const fade=catalog.groups.find(g=>g.id==='knife-500').members.find(s=>s.english==='★ Bayonet | Fade');
let app,page;const errors=[];
async function launch(name){const profile=resolve(root,name);await mkdir(profile,{recursive:true});const env={...process.env,CS_RENT_TEST_DATA:profile};delete env.CS_RENT_TEST_DEMO;delete env.ELECTRON_RUN_AS_NODE;app=await electron.launch({args:['out/main/index.js'],env});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));await page.getByRole('heading',{name:'每一件饰品，都有迹可循。'}).waitFor();return profile;}
const go=name=>page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name,exact:true}).click();
const modal=()=>page.locator('.ant-modal:visible');
const choose=async(label,value)=>{await modal().getByLabel(label,{exact:true}).click();await page.locator('.ant-select-item-option-content:visible').getByText(value,{exact:true}).click();};
const data=async()=>(await page.evaluate(()=>window.desktop.data.get())).data;
const waitState=async(fn,arg)=>{for(let i=0;i<100;i++){if(fn(await data(),arg))return;await new Promise(r=>setTimeout(r,100));}assert.fail('State did not persist');};
const shot=name=>page.screenshot({path:resolve(root,name+'.png'),animations:'disabled'});
try{
 await launch('source');assert.deepEqual((await data()).state,{assets:[],orders:[],wishes:[]});
 await app.evaluate(({ipcMain})=>{ipcMain.removeHandler('market:quote');ipcMain.handle('market:quote',()=>({ok:true,value:123456,source:'测试 SteamDT · BUFF',updated:new Date().toISOString()}));});
 await go('资产与收支');await page.getByRole('button',{name:'新增记录',exact:true}).click();
 await modal().getByLabel('选择商品',{exact:true}).fill(fade.name);await page.locator('.ant-select-item-option-content:visible').getByText(fade.name,{exact:true}).click();
 await choose('外观等级','崭新出厂');await choose('取得方式','受赠');
 assert.equal(await modal().getByLabel('所属平台',{exact:true}).count(),0);
 await modal().getByLabel('实际磨损',{exact:true}).fill('0.0000123400');await modal().getByLabel('图案模板',{exact:true}).fill('387');await modal().getByLabel('渐变率（%）',{exact:true}).fill('98.76500');await shot('40-add-gift-attributes');
 await modal().getByRole('button',{name:'保存记录',exact:true}).click();await modal().waitFor({state:'hidden'});
 await waitState(d=>d.state.assets.length===1);let saved=await data();assert.equal(saved.state.orders.length,0);assert.deepEqual([saved.state.assets[0].platform,saved.state.assets[0].value,saved.state.assets[0].fade],[null,123456,'98.76500']);
 await go('总览');assert.match(await page.locator('.metric').filter({hasText:'库存参考价值'}).innerText(),/1,234\.56/);
 await go('资产与收支');await page.getByRole('button',{name:'查看'+fade.name,exact:true}).click();
 const drawer=()=>page.locator('.ant-drawer:visible');await drawer().getByRole('button',{name:'编辑属性、估值与备注',exact:true}).click();
 await drawer().getByLabel('手动参考价（元）',{exact:true}).fill('2222.22');await drawer().getByRole('button',{name:'保存修改',exact:true}).click();await waitState(d=>d.state.assets[0].value===222222);
 assert.match(await drawer().innerText(),/98\.76500%/);await shot('41-gift-manual-value');await drawer().getByRole('button',{name:'关闭',exact:true}).click();
 await go('收藏室');await page.getByRole('textbox',{name:'搜索全部收藏饰品'}).fill(fade.name);await page.locator('.catalog-search-results button').first().click();assert.match(await page.locator('.collection-banner').innerText(),/刺刀/);assert.equal(await page.getByTestId('collection-count').innerText(),'1 / 25');await shot('42-global-collection-search');
 await go('资产与收支');await page.getByRole('button',{name:'新增记录',exact:true}).click();await choose('记录类型','公共收支');await choose('所属平台','IGXE');
 await modal().getByLabel('公共收支总项名称',{exact:true}).fill('IGXE 公共收支');await modal().getByLabel('首个子项名称',{exact:true}).fill('手续费');await modal().getByLabel('子项初始金额（元）',{exact:true}).fill('10');
 await modal().getByRole('button',{name:'保存记录',exact:true}).click();await modal().waitFor({state:'hidden'});await waitState(d=>d.state.assets.length===2);
 await page.getByRole('button',{name:'查看IGXE 公共收支',exact:true}).click();
 await drawer().getByRole('button',{name:'设置 / 增加金额',exact:true}).click();await modal().getByLabel('增加金额（元）',{exact:true}).fill('2.50');await modal().getByRole('button',{name:'保存子项',exact:true}).click();await modal().waitFor({state:'hidden'});
 await drawer().getByRole('button',{name:'设置 / 增加金额',exact:true}).click();await choose('金额操作','修改当前总额');await modal().getByLabel('当前总额（元）',{exact:true}).fill('15');await modal().getByRole('button',{name:'保存子项',exact:true}).click();await modal().waitFor({state:'hidden'});
 await drawer().getByRole('button',{name:'添加收支子项',exact:true}).click();await modal().getByLabel('子项名称',{exact:true}).fill('放心租费用');await modal().getByLabel('当前总额（元）',{exact:true}).fill('5');await modal().getByRole('button',{name:'保存子项',exact:true}).click();await modal().waitFor({state:'hidden'});
 await drawer().getByRole('button',{name:'添加收支子项',exact:true}).click();await modal().getByLabel('子项名称',{exact:true}).fill('费用返还');await choose('收支方向','收入');await modal().getByLabel('当前总额（元）',{exact:true}).fill('3');await modal().getByRole('button',{name:'保存子项',exact:true}).click();await modal().waitFor({state:'hidden'});
 await waitState(d=>d.state.assets.find(a=>a.kind==='公共收支')?.subitems.length===3);saved=await data();const pub=saved.state.assets.find(a=>a.kind==='公共收支');assert.equal(pub.cost,2000);assert.deepEqual(pub.subitems[0].adjustments.map(a=>a.after),[1000,1250,1500]);await shot('43-public-subitems');
 await drawer().getByRole('button',{name:'调整记录',exact:true}).first().click();assert.match(await modal().innerText(),/12\.50.*15\.00/s);await shot('44-adjustment-history');await modal().getByRole('button',{name:'关闭',exact:true}).click();await drawer().getByRole('button',{name:'关闭',exact:true}).click();
 await go('设置');await page.getByRole('button',{name:'使用深色主题',exact:true}).click();await page.getByRole('switch',{name:'放大文字',exact:true}).click();
 const file=resolve(root,'full-backup.json');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},file);
 await page.getByRole('button',{name:/导出完整备份$/}).click();await page.getByText('完整备份已导出，可在另一台电脑导入',{exact:true}).waitFor();const exported=JSON.parse(await readFile(file,'utf8'));assert.equal(exported.settings.largeText,true);assert.equal(exported.settings.theme,'dark');await shot('45-backup-settings');await app.close();app=null;
 const dest=await launch('destination');assert.deepEqual((await data()).state,{assets:[],orders:[],wishes:[]});
 await go('设置');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},file);
 await page.getByRole('button',{name:/选择备份文件$/}).click();await modal().getByRole('button',{name:'确认恢复备份',exact:true}).waitFor();await shot('46-import-preview');await modal().getByRole('button',{name:'确认恢复备份',exact:true}).click();await page.getByRole('heading',{name:'每一件饰品，都有迹可循。'}).waitFor();
 const restored=await data();assert.deepEqual(restored.state,exported.state);assert.deepEqual(restored.settings,exported.settings);assert.deepEqual(restored.catalog,exported.catalog);assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal((await readdir(dest)).some(n=>n.startsWith('before-restore-')),true);
 await shot('47-restored-overview');
 const invalid=resolve(root,'invalid-backup.json');await writeFile(invalid,JSON.stringify({...exported,schemaVersion:999}));await go('设置');await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},invalid);
 await page.getByRole('button',{name:/选择备份文件$/}).click();await page.getByText('备份格式、版本或记录关联不正确；当前数据未修改。',{exact:true}).waitFor();assert.deepEqual((await data()).state,exported.state);
 assert.deepEqual(errors,[]);await writeFile('artifacts/migration-smoke-result.json',JSON.stringify({passed:true,date:new Date().toISOString(),root,checks:['新安装空账本','受赠无平台无购买订单','磨损模板渐变率精度','自动估值入库存','手动估值覆盖','收藏全目录搜索并定位','公共子项设置及增加金额与历史','备份导出实际文件','第二用户目录完整恢复','导入前保存当前副本','错误版本拒绝导入且原数据不变','主题和字号迁移'],errors},null,2));console.log('PASS: new user data and all migration interactions');
}catch(e){if(page&&!page.isClosed()){await shot('migration-failure');await writeFile(resolve(root,'failure.txt'),await page.locator('body').innerText());}throw e;}finally{if(app)await app.close();}
